search:
  default_moves_to_play: 40
  min_depth: 1
  sequential_depth: 2
  use_quiescent_search: true
  initial_window: 25
transposition_table:
  size: 33554432
  pawn_size: 33554432
tablebases:
  enabled: false
  cache_size: 33554432
move_ordering:
  use_hash_move: true
  use_see: true
  use_killers: true
